# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'veevmobile' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for veevmobile

  # pod 'ReactNativeFabric', :path => '../node_modules/react-native-fabric'

  # pod 'RNBackgroundGeolocation', :path => '../node_modules/react-native-background-geolocation-android'

  # pod 'RNBackgroundFetch', :path => '../node_modules/react-native-background-fetch'
#  pod 'Firebase/Core', '~> 4.13.0'
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  # pod 'RNVectorIcons', :path => 'node_modules/react-native-vector-icons'
  # pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'
  # pod 'react-native-network-info', :path => '../node_modules/react-native-network-info'

  # pod 'react-native-notifications', :path => '../node_modules/react-native-notifications'


    rn_path = '../node_modules/react-native'
    rn_maps_path = '../node_modules/react-native-maps'

#
    pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
    pod 'React', path: rn_path, subspecs: [
    'Core',
    'CxxBridge',
    'DevSupport',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTPushNotification',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
    ]
#
#
    pod 'DoubleConversion', :podspec => "#{rn_path}/third-party-podspecs/DoubleConversion.podspec"
    pod 'GLog', :podspec => "#{rn_path}/third-party-podspecs/GLog.podspec"
    pod 'Folly', :podspec => "#{rn_path}/third-party-podspecs/Folly.podspec"
    
    # react-native-maps dependencies
    pod 'react-native-maps', path: rn_maps_path
    pod 'react-native-google-maps', path: rn_maps_path  # Remove this line if you don't want to support GoogleMaps on iOS
    pod 'GoogleMaps'  # Remove this line if you don't want to support GoogleMaps on iOS
    pod 'Google-Maps-iOS-Utils' # Remove this line if you don't want to support GoogleMaps on iOS
#
#  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

  target 'veevmobileTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'veevmobile-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for veevmobile-tvOS

  target 'veevmobile-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end


post_install do |installer|
    installer.pods_project.targets.each do |target|
        if target.name == 'react-native-google-maps'
            target.build_configurations.each do |config|
                config.build_settings['CLANG_ENABLE_MODULES'] = 'No'
            end
        end
        if target.name == 'yoga'
            target.build_configurations.each do |config|
                config.build_settings['GCC_TREAT_WARNINGS_AS_ERRORS'] = 'NO'
                config.build_settings['GCC_WARN_64_TO_32_BIT_CONVERSION'] = 'NO'
            end
        end
        if target.name == "React"
            target.remove_from_project
        end
    end
end
